### ISSUE TITLE
Add Norwegian Style

### ISSUE THREAD

**Issue by Protarios** [brandonagr/gocupi#28]
It would be a great feature to also support the "Norwegian" Drawing Style, the polargraph project supports.
As this is directly generated by the firmware from an bitmap image and not loaded as an svg, this would be a great addon.
These drawings just look great:
http://www.norwegiancreations.com/2012/04/drawing-machine-part-2/
http://www.polargraph.co.uk/2012/08/norwegian-pixel/

**Comment by brandonagr** [comment]
There is the [imagearc](https://github.com/brandonagr/gocupi/blob/master/gocupi.go#L638) command that should be the equivalent of that drawing style, might have to adjust some of the hardcoded settings to get the best results
