### ISSUE TITLE
code.google.com..

### ISSUE THREAD

**Issue by reaganry** [brandonagr/gocupi#29]
'go get' wont work bc plotinum moved to github. is this in a config file? i dont see it..

package code.google.com/p/plotinum/plot: unable to detect version control system for code.google.com/ path

**Comment by scottvr** [comment]
This issue is resolved.

**Comment by scottvr** [comment]
Oh yeah.. the new pull has one additional line I failed to commit from the
code.google refactor.  Sorry about that.

Trying to do it "right", where I commit to one of my local branches of my
local repo and it's head is my github fork master, which I then ask you to
pull into your girhub master branch is a new workflow for me and one commit
did not make it in the last push you pulled. 9r something like that. :-)

I have never selectively merged using git before but I assume that if you
don't like the added property and usage info or the liberty I took with the
getfloatsfromargs function, that you can merge the one chart.go change and
reject the rest. Just an FYI in case anything in this latest pull request
was nor clear.
